defaultProject: ml-data-warehouse-479502
defaultLocation: US
defaultAssertionDataset: dataform_assertions

vars:
  GA4_DATASET: analytics_264228970
  LOCAL_TIMEZONE: Europe/Copenhagen
  TRANSFORMATIONS_DATASET: clean
  OUTPUTS_DATASET: clean
  QUALITY_DATASET: clean
  LABEL_GENERIC_BRAND: superformlabs
  LABEL_GENERIC_TOOL: ga4dataform
  LABEL_GENERIC_LICENSE_TYPE: core
  LABEL_EXECUTION_OPERATION: daily_workflow
  LABEL_GENERIC_PACKAGE_VERSION: v1-18-0
